[project]
name = "pessoal"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastparquet>=2024.11.0",
    "pandas>=2.3.3",
    "pyarrow>=21.0.0",
    "pypdf>=6.1.1",
    "tabula-py>=2.9.0",
]
