"""init schema

Revision ID: 7098f9b605eb
Revises: e057b35e3c6f
Create Date: 2025-10-10 08:11:22.579777

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7098f9b605eb"
down_revision = "e057b35e3c6f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
